name: Extract Translatable Content from HTML

on:
  workflow_dispatch:
    inputs:
      html_file:
        description: 'Path to the HTML file to process'
        required: true
        default: 'input.html'

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 spacy
          python -m spacy download en_core_web_sm

      - name: Run HTML Extraction
        run: |
          python Merged_V2_with_V1_core.py ${{ github.event.inputs.html_file }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: translation-artifacts
          path: |
            translatable_flat.json
            non_translatable.html
