name: Extract Translatable Content

on:
  workflow_dispatch:
    inputs:
      html_file:
        description: 'Path to the HTML file to process'
        required: true
        default: 'index.html'

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 spacy html5lib langdetect regex pypinyin
          python -m spacy download en_core_web_sm  # Preload default English model
          python -m spacy download zh_core_web_sm
          python -m spacy download fr_core_news_sm
          python -m spacy download es_core_news_sm
          python -m spacy download de_core_news_sm
          python -m spacy download it_core_news_sm
          python -m spacy download pt_core_news_sm
          python -m spacy download ru_core_news_sm
          python -m spacy download el_core_news_sm
          python -m spacy download xx_ent_wiki_sm  # multilingual fallback for Arabic, Hebrew, Thai, Hindi
     
      - name: Run multilingual content extraction
        run: |
          python step1_extract.py "${{ github.event.inputs.html_file }}"

      - name: Upload extracted results
        uses: actions/upload-artifact@v4
        with:
          name: extracted-translatables
          path: |
            translatable_flat.json
            translatable_structured.json
            translatable_flat_sentences.json
            non_translatable.html
