name: Count Languages in JSON

on:
  workflow_dispatch:
    inputs:
      json_filename:
        description: 'Path to the input JSON file (e.g., data/input.json)'
        required: true
        default: 'input.json'

jobs:
  analyze-languages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run language counting script
        run: |
          python count_languages.py ${{ github.event.inputs.json_filename }}
